### ISSUE TITLE
Add keyboard shortcut to full screen button

### ISSUE THREAD

**Issue by fischy667** [Dinoosauro/youtube-fullscreen-fit#7]
The extention has a button to transform a fullscreen video back to its original size. It would be nice when this action also had a (customizable) keyboard shortcut.

**Comment by dinoosauro** [comment]
Hello, sorry for the late reply but I had no time to look this sooner. The new update permits to add a custom keyboard shortcut from the extension's settings UI. I'll upload the new extension now on Firefox Add-ons, so the rollout of the new version might take a few hours. Let me know if you've any other issues

**Comment by fischy667** [comment]
Works perfect. Thanks

**Comment by fischy667** [comment]
Unfortunately, it only seems to work for the first video in a playlist. For all other videos in the list, when pressing the shortcut nothing happens.

**Comment by dinoosauro** [comment]
You're right – thanks for reporting this issue. It turned out that the problem was due to the way the extension handles changing the video. I have fixed this and with version 1.5.1 it should work fine. However, if you find any other issues, let me know and I'll have a look at them
